services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest # 


    container_name: mealie
    restart: always
    ports:
        - "9925:9000" # 


    deploy:
      resources:
        limits:
          memory: 1000M # 


    volumes:
      - mealie-data:/app/data/

volumes:
  mealie-data:
